name: "Release"
on: 
  push:
    branches:
      - master
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
      with: 
        ref: 'master'

    - name: Keep dist up-to-date
      run: |
        npm i
        npm run build
        npm run pack
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
        git add dist/index.js
        git commit -m "chore: publish dist" || echo "nothing to commit"
        git push origin master

    - uses: actions/checkout@v3
      with:
        ref: master
        
    - name: Test Action Dry Run
      uses: ./
      with: 
        VARIABLES: |
          ^FOO$
          ^BAR$
        REPOSITORIES: |
          ^Firenza/verify-secrets$
        DRY_RUN: true
        GITHUB_TOKEN: ${{ secrets.GH_TOKEN_NO_SCOPES }}
      env:
        FOO: ${{github.run_id}}
        BAR: ${{github.run_number}}

    - name: Test Action
      uses: ./
      with: 
        VARIABLES: |
          ^FOO$
          ^BAR$
        REPOSITORIES: |
          ^Firenza/verify-secrets$
        GITHUB_TOKEN: ${{ secrets.GH_TOKEN_VERIFY_SECRETS_VARIBLE_MUTATE }}
      env:
        FOO: ${{github.run_id}}
        BAR: ${{github.run_number}}

    - name: Checkout
      uses: actions/checkout@v3
      with:
        ref: master 
        
    - name: Semantic Release
      run: |
        npm ci
        npx semantic-release
      env:
        GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
